---
title: "slidy features"
output: 
  slidy_presentation:
    duration: 4
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Were did slidy come from?

The slidy_presentation format is based on HTML Slidy, a tool developed by Dave Raggett at W3C designed specifically for creating accessible presentations for the web.

- [Slidy documentation](https://www.w3.org/Talks/Tools/Slidy2/#(1))

It's an extremely popular and versatile format that's still actively developed.

# Benefits of slidy_presentation

There are many benefits of the slidy format:

- Extremely minimal, and easy to customise the style of slides.

- Works *okay* on mobile devices

- Works without JavaScript

- Works well with screen readers, however some keyboard shortcuts conflict with standard hotkeys mappings.

# Disadvantanges of slidy

Some disadvantages of the format:

- The default styles are quite plain and unattractive. Some custom CSS helps brighten up your slides.

- The default font size is small and allows users to include too much content in slides.

# Table of contents in slidy_presentation

There's a table of contents available to `slidy_presentation` users by pressing the `c` key.

# slidy unique feature: Handout mode

Pressing the `a` key will toggle between showing the current slide and all slides together. This is useful for printing slide handouts.

# slidy unique features: Font-size changes

Change your font size to suit your audience's needs with the following keyboard shortcuts:

- `s` for smaller

- `b` for bigger

# slidy unique features: Timer in footer

A timer can be added to the footer via the `duration` option in the YAML header.

    ---
    title: "slidy features"
    output: 
      slidy_presentation:
        duration: 2
    ---

Hide the footer with the `f` key.


# Use these slides as a template!

Consider using this .Rmd file as your template for slidy presentations as it contains all of the features I've explained and a bit more.